### ISSUE TITLE
Fix Contributing Document

### ISSUE THREAD

**Issue by tguo9** [UBC-MDS/samplingsimulatorr#19]
Addressing #18, delete Python parts and edit it for R

**Comment by tguo9** [comment]
link [here](https://github.com/UBC-MDS/samplingsimulatorr/blob/master/CONTRIBUTING.md)

**Comment by YueJiangMDSV** [comment]
Updated the Contributing. Please check the recent pull request. Please review it and let me know if there is anything needs update. Thanks.
