### ISSUE TITLE
Peer Feedback - `generate_virtual_pop` arguments

### ISSUE THREAD

**Issue by hwilliams10** [UBC-MDS/samplingsimulatorr#78]
In `generate_virtual_pop` documentation, description about `dist` seems a bit unclear. For example, `dnorm()`, `dpois()` will not work although it is a function of a distribution. Specifying a list of possible functions that you can use for `dist` in the error message would be super helpful

**Comment by tguo9** [comment]
@hwilliams10 I think this is a common issue for all of our functions.

**Comment by tguo9** [comment]
Neither dnorm() nor dpois() are not suitable under the context of generating a population. So this is what I'm going to do, I will update the documentation.
