### ISSUE TITLE
Peer Feedback - `generate_virtual_pop` function

### ISSUE THREAD

**Issue by hwilliams10** [UBC-MDS/samplingsimulatorr#81]
When I bring up documentation in R Studio, e.g. `?generate_virtual_pop`, the author name is appended to the description of the function. This doesn't seem to be the norm with other packages. I'd consider removing the author line in the source file.

**Comment by tguo9** [comment]
@hwilliams10 I think this is a common issue for all of our functions.

**Comment by tguo9** [comment]
I will just remove the author line as suggested
